apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # external port
      targetPort: 5000 # container port
  type: LoadBalancer
